services:
  postgres:
    image: postgres:16-alpine
    container_name: order-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order_network

volumes:
  postgres_data:

networks:
  order_network:
    name: order_network
