spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: ${DB_USER:order_user}
    password: ${DB_PASSWORD:order_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

